// <auto-generated />
using System;
using FinControl.Lancamentos.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinControl.Lancamentos.Core.Migrations
{
    [DbContext(typeof(LancamentosDbContext))]
    partial class LancamentosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinControl.Lancamentos.Core.Domain.Lancamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por_email");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por_nome");

                    b.Property<DateTimeOffset>("DataLancamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_lancamento");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deletado_por");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("Modalidade")
                        .HasColumnType("integer")
                        .HasColumnName("modalidade");

                    b.Property<Guid?>("NavigationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("navigation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("atualizado_por");

                    b.Property<string>("UpdatedByEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("atualizado_por_email");

                    b.Property<string>("UpdatedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("atualizado_por_nome");

                    b.Property<long>("Valor")
                        .HasColumnType("bigint")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("idx_lancamento_criado_por");

                    b.HasIndex("DataLancamento")
                        .HasDatabaseName("idx_lancamento_data");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_lancamento_deletado");

                    b.HasIndex("NavigationId")
                        .IsUnique()
                        .HasDatabaseName("idx_lancamento_navigation_id");

                    b.HasIndex("CreatedBy", "DataLancamento")
                        .HasDatabaseName("idx_lancamento_criado_por_data");

                    b.HasIndex("DataLancamento", "Modalidade")
                        .HasDatabaseName("idx_lancamento_data_modalidade");

                    b.ToTable("lancamentos", "lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
